<script setup lang="ts">
import { computed } from 'vue';
import {
  LayoutDashboard,
  Ticket,
  MessagesSquare,
  BookOpen,
  ChevronDown,
  ChevronRight,
  ArrowUpRight,
  ArrowLeft,
  ArrowRight,
  Search,
  Plus,
  SlidersHorizontal,
  MoreHorizontal,
  Bell,
  Command,
  LogOut,
  Sparkles,
  LifeBuoy,
  PanelLeft,
  Check,
  CheckCircle2,
  Clock,
  Circle,
  X,
  FileText,
  Upload,
  ExternalLink,
  Copy,
  Send,
  Square,
  RefreshCw,
  Trash2,
  ArrowDown,
  ShieldCheck,
  AlertCircle,
  UserRound,
  Inbox,
  Paperclip,
  Settings,
  Info,
  LoaderCircle,
  Pencil,
} from 'lucide-vue-next';
const props = withDefaults(defineProps<{ name: string; size?: number }>(), { size: 18 });
const icons: Record<string, any> = {
  dashboard: LayoutDashboard,
  ticket: Ticket,
  chat: MessagesSquare,
  book: BookOpen,
  down: ChevronDown,
  right: ChevronRight,
  upRight: ArrowUpRight,
  back: ArrowLeft,
  arrow: ArrowRight,
  search: Search,
  plus: Plus,
  filter: SlidersHorizontal,
  more: MoreHorizontal,
  bell: Bell,
  command: Command,
  logout: LogOut,
  sparkles: Sparkles,
  help: LifeBuoy,
  panel: PanelLeft,
  check: Check,
  done: CheckCircle2,
  clock: Clock,
  circle: Circle,
  x: X,
  file: FileText,
  upload: Upload,
  external: ExternalLink,
  copy: Copy,
  send: Send,
  stop: Square,
  retry: RefreshCw,
  trash: Trash2,
  bottom: ArrowDown,
  shield: ShieldCheck,
  alert: AlertCircle,
  user: UserRound,
  inbox: Inbox,
  clip: Paperclip,
  settings: Settings,
  info: Info,
  loader: LoaderCircle,
  edit: Pencil,
};
const icon = computed(() => icons[props.name] || Circle);
</script>
<template><component :is="icon" :size="size" :stroke-width="1.7" aria-hidden="true" /></template>
